//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPI_Beta_v1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CPI_Beta_v1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1406094705_Generate_tables {
            get {
                object obj = ResourceManager.GetObject("1406094705_Generate-tables", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1406094743_edit_clear {
            get {
                object obj = ResourceManager.GetObject("1406094743_edit-clear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExcelBuilder_GenerateExcel_Error.
        /// </summary>
        internal static string ExcelBuilder_GenerateExcel_Error {
            get {
                return ResourceManager.GetString("ExcelBuilder_GenerateExcel_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AVISO.
        /// </summary>
        internal static string Form1_button2_Click_AVISO {
            get {
                return ResourceManager.GetString("Form1_button2_Click_AVISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O sistema não consegue interpretar o ficheiro!.
        /// </summary>
        internal static string Form1_button2_Click_O_sistema_não_consegue_interpretar_o_ficheiro_ {
            get {
                return ResourceManager.GetString("Form1_button2_Click_O_sistema_não_consegue_interpretar_o_ficheiro_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arraste o ficheiro 
        ///         ou.
        /// </summary>
        internal static string Form1_Form1_Load_ {
            get {
                return ResourceManager.GetString("Form1_Form1_Load_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exists!!.
        /// </summary>
        internal static string Form1_panel2_DragDrop_File_does_not_exists__ {
            get {
                return ResourceManager.GetString("Form1_panel2_DragDrop_File_does_not_exists__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format not allowed.
        /// </summary>
        internal static string Form1_panel2_DragDrop_File_format_not_allowed {
            get {
                return ResourceManager.GetString("Form1_panel2_DragDrop_File_format_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files (.txt)|*.txt.
        /// </summary>
        internal static string Form1_textBox1_MouseDoubleClick_Text_Files___txt____txt {
            get {
                return ResourceManager.GetString("Form1_textBox1_MouseDoubleClick_Text_Files___txt____txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imageTXT {
            get {
                object obj = ResourceManager.GetObject("imageTXT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
